### ISSUE TITLE
ImportError: No module named flask.ext

### ISSUE THREAD

**Issue by imstand** [gae-init/phonebook#1]
By following the tutorial http://docs.gae-init.appspot.com/tutorial/, always error with message:

[22:43:36] --------DONE ----------------------------------------------
INFO     2014-09-18 14:43:38,541 devappserver2.py:725] Skipping SDK update check.
WARNING  2014-09-18 14:43:38,546 api_server.py:383] Could not initialize images API; you are likely missing the Python "PIL" module.
INFO     2014-09-18 14:43:38,580 api_server.py:171] Starting API server at: http://localhost:49195
INFO     2014-09-18 14:43:38,609 dispatcher.py:183] Starting module "default" running at: http://127.0.0.1:8080
INFO     2014-09-18 14:43:38,639 admin_server.py:117] Starting admin server at: http://localhost:8081
ERROR    2014-09-18 14:43:40,766 wsgi.py:262] 
Traceback (most recent call last):
  File "/Users/Alpha/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 239, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/Alpha/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 298, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/Alpha/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 84, in LoadObject
    obj = __import__(path[0])
  File "/Users/Alpha/Downloads/phonebook/main/main.py", line 5, in <module>
    from flask.ext import wtf
ImportError: No module named flask.ext
INFO     2014-09-18 14:43:40,776 module.py:652] default: "GET /_ah/warmup HTTP/1.1" 500 -

**Comment by jazware** [comment]
I'm also having this error...

./run.py -C
[16:53:12] ---CLEAN ALL ----------------------------------------------
[16:53:12]  CLEAN FILES Removing files: *pyc, *pyo, *~
[16:53:14]    NOT FOUND Internet
[16:53:14] -------CLEAN ----------------------------------------------
[16:53:14]  CLEAN FILES Removing files: *pyc, *pyo, *~
[16:53:14]    NOT FOUND main/lib
[16:53:14]         LESS main/static/src/style/style.less
sh: node_modules/.bin/lessc: No such file or directory
[16:53:14]    NOT FOUND main/static/ext/jquery/dist/jquery.js
[16:53:14]    NOT FOUND main/static/ext/moment/moment.js
[16:53:14]    NOT FOUND main/static/ext/nprogress/nprogress.js
[16:53:14]    NOT FOUND main/static/ext/bootstrap/js/alert.js
[16:53:14]    NOT FOUND main/static/ext/bootstrap/js/button.js
[16:53:14]    NOT FOUND main/static/ext/bootstrap/js/transition.js
[16:53:14]    NOT FOUND main/static/ext/bootstrap/js/collapse.js
[16:53:14]    NOT FOUND main/static/ext/bootstrap/js/dropdown.js
[16:53:14]    NOT FOUND main/static/ext/bootstrap/js/tooltip.js
[16:53:14]       COFFEE main/static/src/script/common/api.coffee
sh: node_modules/.bin/coffee: No such file or directory
[16:53:14]       COFFEE main/static/src/script/common/util.coffee
sh: node_modules/.bin/coffee: No such file or directory
[16:53:14]       COFFEE main/static/src/script/site/app.coffee
sh: node_modules/.bin/coffee: No such file or directory
[16:53:14]       COFFEE main/static/src/script/site/admin.coffee
sh: node_modules/.bin/coffee: No such file or directory
[16:53:14]       COFFEE main/static/src/script/site/auth.coffee
sh: node_modules/.bin/coffee: No such file or directory
[16:53:14]       COFFEE main/static/src/script/site/user.coffee
sh: node_modules/.bin/coffee: No such file or directory
[16:53:14] --------DONE ----------------------------------------------
ev-rmbp:phonebook ericvolp$ ./run.py -s
[16:53:17]    NOT FOUND Internet
[16:53:18] -------CLEAN ----------------------------------------------
[16:53:18]  CLEAN FILES Removing files: *pyc, *pyo, *~
[16:53:18]    NOT FOUND main/lib
[16:53:18]         LESS main/static/src/style/style.less
sh: node_modules/.bin/lessc: No such file or directory
[16:53:18]    NOT FOUND main/static/ext/jquery/dist/jquery.js
[16:53:18]    NOT FOUND main/static/ext/moment/moment.js
[16:53:18]    NOT FOUND main/static/ext/nprogress/nprogress.js
[16:53:18]    NOT FOUND main/static/ext/bootstrap/js/alert.js
[16:53:18]    NOT FOUND main/static/ext/bootstrap/js/button.js
[16:53:18]    NOT FOUND main/static/ext/bootstrap/js/transition.js
[16:53:18]    NOT FOUND main/static/ext/bootstrap/js/collapse.js
[16:53:18]    NOT FOUND main/static/ext/bootstrap/js/dropdown.js
[16:53:18]    NOT FOUND main/static/ext/bootstrap/js/tooltip.js
[16:53:18]       COFFEE main/static/src/script/common/api.coffee
sh: node_modules/.bin/coffee: No such file or directory
[16:53:18]       COFFEE main/static/src/script/common/util.coffee
sh: node_modules/.bin/coffee: No such file or directory
[16:53:18]       COFFEE main/static/src/script/site/app.coffee
sh: node_modules/.bin/coffee: No such file or directory
[16:53:18]       COFFEE main/static/src/script/site/admin.coffee
sh: node_modules/.bin/coffee: No such file or directory
[16:53:18]       COFFEE main/static/src/script/site/auth.coffee
sh: node_modules/.bin/coffee: No such file or directory
[16:53:18]       COFFEE main/static/src/script/site/user.coffee
sh: node_modules/.bin/coffee: No such file or directory
[16:53:18] --------DONE ----------------------------------------------
INFO     2015-04-22 15:53:18,617 devappserver2.py:745] Skipping SDK update check.
INFO     2015-04-22 15:53:18,664 api_server.py:190] Starting API server at: http://localhost:63877
INFO     2015-04-22 15:53:18,668 dispatcher.py:192] Starting module "default" running at: http://127.0.0.1:8080
INFO     2015-04-22 15:53:18,670 admin_server.py:118] Starting admin server at: http://localhost:8081
ERROR    2015-04-22 15:53:21,059 wsgi.py:263] 
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/ericvolp/Documents/App Engine/phonebook/main/main.py", line 3, in <module>
    import flask
ImportError: No module named flask
INFO     2015-04-22 15:53:21,064 module.py:788] default: "GET /_ah/warmup HTTP/1.1" 500 749
ERROR    2015-04-22 15:53:23,951 wsgi.py:263] 
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/ericvolp/Documents/App Engine/phonebook/main/main.py", line 3, in <module>
    import flask
ImportError: No module named flask
INFO     2015-04-22 15:53:23,956 module.py:788] default: "GET / HTTP/1.1" 500 749
INFO     2015-04-22 15:53:24,115 module.py:788] default: "GET /favicon.ico HTTP/1.1" 304 -

**Comment by gmist** [comment]
Maybe problem is here

```
[16:53:14] NOT FOUND Internet
```

**Comment by jazware** [comment]
How would I fix that? I'm obviously connected to the internet...

**Comment by gmist** [comment]
74.125.228.100 which is used for checking internet connection is no longer available. Just replace `run.py` line 127 to:

``` python
INERNET_TEST_URL = 'http://64.233.164.101'
```

**Comment by jazware** [comment]
That should probably be updated in the repo btw XD

**Comment by jazware** [comment]
Still getting tons of errors. There's no folder main/static/ext and it keeps calling it...

**Comment by lipis** [comment]
The Phonebook project is a bit outdated.. and there were updates in run.py regarding the latest google cloud SDK..

**Comment by jazware** [comment]
What tutorial should I use then?

**Comment by lipis** [comment]
the tutorial should work.. but this current repo is kind of dated.. so if you start from https://github.com/gae-init/gae-init it _should_ work..

**Comment by lipis** [comment]
https://github.com/gae-init/gae-init/pull/343
